[language-server]
nimlsp = {command = "nimlsp"}
glslls = {command = "glslls"}

[language-sever.nimlsp]
command = "nimlsp"


[[language]]
name = "nim"
scope = "source.nim"
injection-regex = "nim"
file-types = ["nim", "nims", "nimble"]
shebangs = []
roots = []
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
language-servers = ["nimlsp"]
auto-format = true


[language-sever.glslls]
command = "glslls"

[[language]]
name = "glsl"
scope = "source.glsl"
file-types = ["glsl", "vert", "tesc", "tese", "geom", "frag", "comp" ]
roots = []
comment-token = "//"
indent = { tab-width = 4, unit = "    " }
injection-regex = "glsl"
language-servers = ["glslls"]
